### ISSUE TITLE
Apply name-resolution also to verification output

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/aqua-verifier-webextension#60]
There is a quite critical issue for us, that the name-resolution which works on the page with the content_script is not applied to the print out of the verification data.

The user expects to have a consistent name resolution and will be shocked to see a 'naked' wallet address ;)

**Comment by FantasticoFox** [comment]
Example where name resolution should be applied:
![image](https://user-images.githubusercontent.com/45313235/150255215-d5dcd004-08e8-43ee-b3d0-900b6d5243c1.png)

In the header of the page:
![image](https://user-images.githubusercontent.com/45313235/150255378-bc9966de-81a2-4af1-bc46-1d13b2e4bbfd.png)

Example of nameresolution: This is applied in pages like this https://playground.inblock.io/index.php/0xa2026582b94feb9124231fbf7b052c39218954c2:ANS
![image](https://user-images.githubusercontent.com/45313235/150257002-430a6943-493a-453a-93d9-084c8e1388dd.png)

If you copy the names and wallet addresses into your ANS then it will allow you to resolve all those wallets in the page via a content_script. Please reach out if you need more context @lobogang

**Comment by FantasticoFox** [comment]
![image](https://user-images.githubusercontent.com/45313235/150260770-9519156c-7f7f-46d3-b3b1-3d06408bd871.png)

Content Wallet-Addresses in the external verifier should also be resolved.

**Comment by rht** [comment]
Fixed in https://github.com/inblockio/aqua-verifier-webextension/commit/276bfffebdb8d1337a3bf44ffc9584de33fd37ba, https://github.com/inblockio/aqua-verifier-webextension/commit/2918201fb7837c9bebb43ccdf510dc6e02b3053a, https://github.com/inblockio/aqua-verifier-webextension/commit/17b28b493ba17ef46b9e444331e732fcd42323e7, https://github.com/inblockio/aqua-verifier-webextension/commit/1524a31580a3da8623cb0e0e5fa0630463fb45ad.

**Comment by lobogang** [comment]
thanks for that fix @rht , I'll merge new main into my PR (https://github.com/inblockio/aqua-verifier-webextension/pull/62) before going forward with offline_verification updates
